version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.1
  node: 'circleci/node:4.1'
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run deploy
      - slack/notify:
          channel: Simple ode Api
          event: fail
          template: basic_fail_1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
  deploy_and_notify:
    jobs:
      - deploy:
          context: slack-secrets
