version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
